#############################################################################
# Makefile for building: median_test
# Generated by qmake (3.1) (Qt 5.13.1)
# Project:  MedianFilter.pro
# Template: app
# Command: /home/mahdi/Qt5.13.1/5.13.1/gcc_64/bin/qmake -o Makefile MedianFilter.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/opencv4/include/opencv4 -I/usr/local/cuda/include -I/usr/local/cuda/samples/common/inc -I/usr/local/opencv4/include/opencv4 -I../../Qt5.13.1/5.13.1/gcc_64/include -I../../Qt5.13.1/5.13.1/gcc_64/include/QtGui -I../../Qt5.13.1/5.13.1/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../Qt5.13.1/5.13.1/gcc_64/mkspecs/linux-g++
QMAKE         = /home/mahdi/Qt5.13.1/5.13.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/mahdi/Qt5.13.1/5.13.1/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/mahdi/Qt5.13.1/5.13.1/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = median_test1.0.0
DISTDIR = /home/mahdi/Downloads/MedianFilter/.tmp/median_test1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/mahdi/Qt5.13.1/5.13.1/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/opencv4/lib -lopencv_tracking -lopencv_video -lopencv_calib3d -lopencv_photo -lopencv_ximgproc -lopencv_cudawarping -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_cudaarithm -lopencv_imgcodecs -lopencv_features2d -lopencv_ml -lopencv_cudaobjdetect -L/usr/local/cuda/lib64 -L/usr/local/cuda/samples/common/lib/linux -L/usr/local/cuda/samples/common/lib/linux/stubs -lopencv_core -lopencv_imgproc -lopencv_highgui -lcudart /home/mahdi/Qt5.13.1/5.13.1/gcc_64/lib/libQt5Gui.so /home/mahdi/Qt5.13.1/5.13.1/gcc_64/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = cuda/median_cuda.o \
		cuda/median_cuda_link.o \
		main.o
DIST          = ../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/link_pkgconfig.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/lex.prf \
		MedianFilter.pro cuda_externs.h main.cpp
QMAKE_TARGET  = median_test
DESTDIR       = 
TARGET        = median_test


first: all
####### Build rules

median_test:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MedianFilter.pro ../../Qt5.13.1/5.13.1/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/unix.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/linux.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/qconfig.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/default_post.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/link_pkgconfig.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qt.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/resources.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/moc.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/yacc.prf \
		../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/lex.prf \
		MedianFilter.pro
	$(QMAKE) -o Makefile MedianFilter.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/unix.conf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/linux.conf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/sanitize.conf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/g++-base.conf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/qconfig.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qt_config.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/toolchain.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/default_pre.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/default_post.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/link_pkgconfig.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qml_debug.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/warn_on.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qt.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/resources.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/moc.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/unix/opengl.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/qmake_use.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/file_copies.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/exceptions.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/yacc.prf:
../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/lex.prf:
MedianFilter.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile MedianFilter.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile median_test

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents median.cu $(DISTDIR)/
	$(COPY_FILE) --parents cuda/median_cuda.o $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents cuda_externs.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_nvcc_command_make_all: cuda/median_cuda.o
compiler_nvcc_command_clean:
	-$(DEL_FILE) cuda/*.o
cuda/median_cuda.o: median.cu \
		/usr/local/opencv4/include/opencv4/opencv2/core/cuda.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/opencv4/include/opencv4/opencv2/core/version.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/opencv4/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/opencv4/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/opencv4/include/opencv4/opencv2/core/hal/msa_macros.h \
		/usr/local/opencv4/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/base.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/check.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/types.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/utils/instrumentation.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/utils/tls.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/cuda_types.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/cuda.inl.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/cuda_stream_accessor.hpp \
		/usr/local/cuda/include/cuda_runtime.h \
		/usr/local/cuda/include/crt/host_config.h \
		/usr/local/cuda/include/builtin_types.h \
		/usr/local/cuda/include/device_types.h \
		/usr/local/cuda/include/crt/host_defines.h \
		/usr/local/cuda/include/driver_types.h \
		/usr/local/cuda/include/vector_types.h \
		/usr/local/cuda/include/surface_types.h \
		/usr/local/cuda/include/texture_types.h \
		/usr/local/cuda/include/library_types.h \
		/usr/local/cuda/include/channel_descriptor.h \
		/usr/local/cuda/include/cuda_runtime_api.h \
		/usr/local/cuda/include/cuda_device_runtime_api.h \
		/usr/local/cuda/include/driver_functions.h \
		/usr/local/cuda/include/vector_functions.h \
		/usr/local/cuda/include/vector_functions.hpp \
		/usr/local/cuda/include/crt/device_functions.h \
		/usr/local/cuda/include/crt/device_functions.hpp \
		/usr/local/cuda/include/device_atomic_functions.h \
		/usr/local/cuda/include/device_atomic_functions.hpp \
		/usr/local/cuda/include/crt/device_double_functions.h \
		/usr/local/cuda/include/crt/device_double_functions.hpp \
		/usr/local/cuda/include/sm_20_atomic_functions.h \
		/usr/local/cuda/include/sm_20_atomic_functions.hpp \
		/usr/local/cuda/include/sm_32_atomic_functions.h \
		/usr/local/cuda/include/sm_32_atomic_functions.hpp \
		/usr/local/cuda/include/sm_35_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.h \
		/usr/local/cuda/include/sm_60_atomic_functions.hpp \
		/usr/local/cuda/include/sm_20_intrinsics.h \
		/usr/local/cuda/include/sm_20_intrinsics.hpp \
		/usr/local/cuda/include/sm_30_intrinsics.h \
		/usr/local/cuda/include/sm_30_intrinsics.hpp \
		/usr/local/cuda/include/sm_32_intrinsics.h \
		/usr/local/cuda/include/sm_32_intrinsics.hpp \
		/usr/local/cuda/include/sm_35_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.h \
		/usr/local/cuda/include/sm_61_intrinsics.hpp \
		/usr/local/cuda/include/crt/sm_70_rt.h \
		/usr/local/cuda/include/crt/sm_70_rt.hpp \
		/usr/local/cuda/include/crt/sm_80_rt.h \
		/usr/local/cuda/include/crt/sm_80_rt.hpp \
		/usr/local/cuda/include/surface_functions.h \
		/usr/local/cuda/include/cuda_surface_types.h \
		/usr/local/cuda/include/texture_fetch_functions.h \
		/usr/local/cuda/include/cuda_texture_types.h \
		/usr/local/cuda/include/texture_indirect_functions.h \
		/usr/local/cuda/include/surface_indirect_functions.h \
		/usr/local/cuda/include/crt/common_functions.h \
		/usr/local/cuda/include/crt/math_functions.h \
		/usr/local/cuda/include/crt/func_macro.h \
		/usr/local/cuda/include/crt/math_functions.hpp \
		/usr/local/cuda/include/math_constants.h \
		/usr/local/cuda/include/device_launch_parameters.h
	/usr/local/cuda/bin/nvcc -D_DEBUG -use_fast_math -I"/usr/local/opencv4/include/opencv4" -I"/usr/local/cuda/include" -I"/usr/local/cuda/samples/common/inc" -I"/usr/local/opencv4/include/opencv4" -L/usr/local/opencv4/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_tracking -lopencv_video -lopencv_calib3d -lopencv_photo -lopencv_ximgproc -lopencv_cudawarping -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_cudaarithm -lopencv_imgcodecs -lopencv_features2d -lopencv_ml -lopencv_cudaobjdetect -L/usr/local/cuda/lib64 -L/usr/local/cuda/samples/common/lib/linux -L/usr/local/cuda/samples/common/lib/linux/stubs -L/usr/local/opencv4/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lcudart --machine 64 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -dc -o cuda/median_cuda.o -c median.cu

compiler_nvcc_linker_make_all: cuda/median_cuda_link.o
compiler_nvcc_linker_clean:
	-$(DEL_FILE) cuda/median_cuda_link.o
cuda/median_cuda_link.o: cuda/median_cuda.o
	/usr/local/cuda/bin/nvcc -D_DEBUG -L/usr/local/opencv4/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_tracking -lopencv_video -lopencv_calib3d -lopencv_photo -lopencv_ximgproc -lopencv_cudawarping -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_cudaarithm -lopencv_imgcodecs -lopencv_features2d -lopencv_ml -lopencv_cudaobjdetect -L/usr/local/cuda/lib64 -L/usr/local/cuda/samples/common/lib/linux -L/usr/local/cuda/samples/common/lib/linux/stubs -L/usr/local/opencv4/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -lcudart --machine 64 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_60,code=sm_60 -gencode arch=compute_61,code=sm_61 -gencode arch=compute_70,code=sm_70 -gencode arch=compute_75,code=sm_75 -gencode arch=compute_80,code=sm_80 -dlink -o cuda/median_cuda_link.o cuda/median_cuda.o

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -Wall -W -dM -E -o moc_predefs.h ../../Qt5.13.1/5.13.1/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_nvcc_command_clean compiler_nvcc_linker_clean compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp cuda_externs.h \
		/usr/local/opencv4/include/opencv4/opencv2/core/cuda.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/cvdef.h \
		/usr/local/opencv4/include/opencv4/opencv2/core/version.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/hal/interface.h \
		/usr/local/opencv4/include/opencv4/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/opencv4/include/opencv4/opencv2/core/cv_cpu_helper.h \
		/usr/local/opencv4/include/opencv4/opencv2/core/hal/msa_macros.h \
		/usr/local/opencv4/include/opencv4/opencv2/core/fast_math.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/base.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/opencv_modules.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/cvstd.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/cvstd_wrapper.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/neon_utils.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/vsx_utils.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/check.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/traits.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/matx.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/saturate.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/types.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/mat.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/bufferpool.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/mat.inl.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/persistence.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/operations.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/cvstd.inl.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/utility.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/utils/instrumentation.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/utils/tls.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/optim.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/ovx.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/cuda_types.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/core/cuda.inl.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/imgcodecs.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/highgui.hpp \
		/usr/local/opencv4/include/opencv4/opencv2/videoio.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

